on:
  push:
    branches:
      - master
jobs:
  build-test:
    name: Test Building
    runs-on: ubuntu-latest
    steps:
    - name: Checkout blank project
      uses: actions/checkout@v4
      with:
        repository: areyoutoo/Unity3D-EmptyProject
        path: .
    - uses: actions/checkout@v4
      with:
        path: Packages/WorkBoard
    - run: mkdir Assets
    - uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: StandaloneLinux64
        unityVersion: 2021.3.31f1
